package saferis

/** Type-safe representation of SQL table aliases.
  *
  * Aliases are used to qualify column references in SQL queries. This sealed trait distinguishes between:
  *   - Generated aliases (safe by construction, no escaping needed)
  *   - User-supplied aliases (require escaping for SQL injection safety)
  */
sealed trait Alias:
  /** The raw alias string value */
  def value: String

  /** Convert the alias to its SQL representation.
    *
    * Generated aliases are rendered as-is since they are safe by construction. User-supplied aliases are escaped using
    * the dialect's identifier quoting rules.
    */
  def toSql(using Dialect): String

object Alias:
  /** An internally generated alias (e.g., t1, t2, t3).
    *
    * These are safe by construction since they are generated by the library, not user input.
    */
  final case class Generated(value: String) extends Alias:
    def toSql(using Dialect): String = value

  /** A user-supplied alias that requires escaping for SQL injection safety. */
  final case class User(value: String) extends Alias:
    def toSql(using Dialect): String = summon[Dialect].escapeIdentifier(value)
