package saferis

import zio.*

import java.sql.ResultSet
import scala.annotation.StaticAnnotation

/** Represents a label for a column in a result set. Fields in a case class can be annotated with this to specify the
  * column name/label Example:
  * {{{
  *   case class User(
  *     @label("user_id") id: Int,
  *     @label("user_name") name: String
  *   )
  * }}}
  *
  * @param name
  */
final case class label(name: String) extends StaticAnnotation

/** denotes fields of a case class that are generated by the database
  */
class generated extends key

/** denotes fields of a case class that make up a primary key
  */
class key extends StaticAnnotation

/** Represents a column/field in result set
  *
  * @param name
  *   the scala field name in the case class
  * @param label
  *   the column name/label in the result set
  * @param reader
  */
final case class Column[R: Decoder as readable: Encoder as writable](
    name: String,
    label: String,
    isKey: Boolean,
    isGenerated: Boolean,
    isNullable: Boolean,
    defaultValue: Option[R],
    tableAlias: Option[Alias],
) extends Placeholder:
  type ColumnType = R
  val writes = Seq.empty
  // Note: We cannot access dialect here as Column is constructed at compile-time
  // The label should already be the raw identifier
  // For generated aliases, we use the value directly (no escaping needed)
  // For user aliases, escaping will happen at the condition level where Dialect is available
  val sql = tableAlias.fold(label)(a => s"${a.value}.$label")

  private[saferis] def read(rs: ResultSet)(using Trace): Task[(String, R)] =
    readable.decode(rs, label).map(v => name -> v)
  private[saferis] def withTableAlias(alias: Option[Alias]) = copy(tableAlias = alias)

  // Provide SQL type information based on the encoder
  private[saferis] def sqlType: Int                                                          = writable.jdbcType
  private[saferis] def columnType(using dialect: Dialect = postgres.PostgresDialect): String =
    writable.columnType

  /** Returns the DEFAULT clause for DDL if a default value is defined */
  private[saferis] def defaultClause: Option[String] =
    defaultValue.map(v => s"default ${writable.literal(v)}")
end Column
